import { EditorView } from "@codemirror/view";

export const slashMenuTheme = EditorView.baseTheme({
  ".cm-markora-slash-menu": {
    position: "fixed",
    display: "flex",
    flexDirection: "column",
    zIndex: "1000",
    width: "328px",
    maxHeight: "420px",
    overflow: "hidden",
    border: "1px solid rgba(120, 113, 108, 0.22)",
    borderRadius: "12px",
    background: "var(--markora-slash-bg, #ffffff)",
    boxShadow: "0 18px 48px rgba(15, 23, 42, 0.16)",
    padding: "8px 0 0",
    caretColor: "transparent",
    cursor: "default",
    fontFamily: "var(--font-sans, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif)",
    userSelect: "none",
  },
  ".cm-markora-slash-open .cm-cursor": {
    visibility: "hidden",
  },
  ".cm-markora-slash-open .cm-content": {
    caretColor: "transparent",
  },
  ".cm-markora-slash-list": {
    flex: "1 1 auto",
    minHeight: "0",
    overflowY: "auto",
  },
  ".cm-markora-slash-group": {
    padding: "8px 14px 6px",
    color: "var(--markora-slash-muted, #a8a29e)",
    fontSize: "12px",
    fontWeight: "500",
  },
  ".cm-markora-slash-item": {
    display: "grid",
    gridTemplateColumns: "34px 1fr auto",
    alignItems: "center",
    width: "100%",
    minHeight: "34px",
    border: "0",
    padding: "0 14px",
    background: "transparent",
    color: "var(--markora-slash-fg, #27272a)",
    textAlign: "left",
    cursor: "default",
  },
  ".cm-markora-slash-item-active": {
    background: "var(--markora-slash-active, #f4f4f5)",
  },
  ".cm-markora-slash-icon": {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--markora-slash-icon, #3f3f46)",
    fontSize: "13px",
    fontWeight: "400",
    textAlign: "center",
  },
  ".cm-markora-slash-icon svg": {
    display: "block",
    width: "17px",
    height: "17px",
    strokeWidth: "1.9",
  },
  ".cm-markora-slash-title": {
    overflow: "hidden",
    color: "inherit",
    fontSize: "14px",
    fontWeight: "400",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  ".cm-markora-slash-hint": {
    marginLeft: "12px",
    color: "var(--markora-slash-muted, #a8a29e)",
    fontSize: "12px",
    fontWeight: "400",
  },
  ".cm-markora-slash-footer": {
    display: "flex",
    flex: "0 0 auto",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: "40px",
    borderTop: "1px solid rgba(120, 113, 108, 0.18)",
    background: "var(--markora-slash-bg, #ffffff)",
    padding: "0 14px",
    color: "var(--markora-slash-fg, #27272a)",
    fontSize: "14px",
  },
  ".cm-markora-slash-footer span:last-child": {
    color: "var(--markora-slash-muted, #a8a29e)",
    fontSize: "12px",
    fontWeight: "400",
  },
  ".cm-markora-slash-empty": {
    padding: "14px",
    color: "var(--markora-slash-muted, #a8a29e)",
    fontSize: "13px",
  },
  "&dark .cm-markora-slash-menu": {
    "--markora-slash-bg": "#18181b",
    "--markora-slash-fg": "#f4f4f5",
    "--markora-slash-muted": "#a1a1aa",
    "--markora-slash-active": "#27272a",
    "--markora-slash-icon": "#e4e4e7",
  },
});
