import { createTheme } from "./utils";

export const mediaLightboxTheme = createTheme({
  default: {
    ".cm-mardora-media-preview": {
      position: "relative",
    },
    ".cm-mardora-media-preview-button": {
      position: "absolute",
      top: "0.5rem",
      right: "0.5rem",
      width: "1.75rem",
      height: "1.75rem",
      border: "1px solid rgba(148, 163, 184, 0.45)",
      borderRadius: "0.375rem",
      backgroundColor: "rgba(255, 255, 255, 0.86)",
      color: "#334155",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      padding: "0",
      opacity: "0",
      pointerEvents: "auto",
      cursor: "pointer",
      transition: "opacity 120ms ease, background-color 120ms ease, border-color 120ms ease",
      zIndex: "2",
    },
    ".cm-mardora-media-preview:hover .cm-mardora-media-preview-button, .cm-mardora-media-preview-button:focus-visible": {
      opacity: "1",
    },
    ".cm-mardora-media-preview-button:hover, .cm-mardora-media-preview-button:focus-visible": {
      borderColor: "rgba(37, 99, 235, 0.55)",
      backgroundColor: "rgba(255, 255, 255, 0.96)",
      color: "#2563eb",
      outline: "none",
    },
    ".cm-mardora-media-preview-button svg": {
      width: "1rem",
      height: "1rem",
    },
    ".cm-mardora-media-lightbox": {
      position: "fixed",
      inset: "0",
      zIndex: "10000",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      padding: "2rem",
      backgroundColor: "rgba(15, 23, 42, 0.24)",
    },
    ".cm-mardora-media-lightbox-panel": {
      position: "relative",
      width: "min(96vw, 1200px)",
      maxWidth: "min(96vw, 1200px)",
      maxHeight: "92vh",
      borderRadius: "0.75rem",
      backgroundColor: "#ffffff",
      color: "#0f172a",
      boxShadow: "0 24px 70px rgba(15, 23, 42, 0.28)",
      overflow: "hidden",
    },
    ".cm-mardora-media-lightbox-body": {
      maxWidth: "100%",
      maxHeight: "92vh",
      overflow: "auto",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      padding: "1rem",
    },
    ".cm-mardora-media-lightbox-image": {
      display: "block",
      maxWidth: "100%",
      maxHeight: "calc(92vh - 2rem)",
      width: "auto",
      height: "auto",
      objectFit: "contain",
    },
    ".cm-mardora-media-lightbox-html": {
      width: "100%",
      maxWidth: "100%",
      maxHeight: "calc(92vh - 2rem)",
      overflow: "auto",
      display: "flex",
      justifyContent: "center",
    },
    ".cm-mardora-media-lightbox-html svg": {
      display: "block",
      maxWidth: "100%",
      maxHeight: "calc(92vh - 2rem)",
      width: "100%",
      height: "auto",
    },
    ".cm-mardora-media-lightbox-close": {
      position: "absolute",
      top: "0.5rem",
      right: "0.5rem",
      width: "2rem",
      height: "2rem",
      border: "1px solid rgba(148, 163, 184, 0.45)",
      borderRadius: "0.375rem",
      backgroundColor: "rgba(255, 255, 255, 0.92)",
      color: "#334155",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      padding: "0",
      cursor: "pointer",
    },
    ".cm-mardora-media-lightbox-close:hover, .cm-mardora-media-lightbox-close:focus-visible": {
      borderColor: "rgba(37, 99, 235, 0.55)",
      color: "#2563eb",
      outline: "none",
    },
    ".cm-mardora-media-lightbox-close svg": {
      width: "1rem",
      height: "1rem",
    },
  },
  dark: {
    ".cm-mardora-media-preview-button": {
      borderColor: "rgba(71, 85, 105, 0.72)",
      backgroundColor: "rgba(15, 23, 42, 0.84)",
      color: "#cbd5e1",
    },
    ".cm-mardora-media-preview-button:hover, .cm-mardora-media-preview-button:focus-visible": {
      borderColor: "rgba(96, 165, 250, 0.68)",
      backgroundColor: "rgba(15, 23, 42, 0.96)",
      color: "#93c5fd",
    },
    ".cm-mardora-media-lightbox-panel": {
      backgroundColor: "#0f172a",
      color: "#e2e8f0",
      boxShadow: "0 24px 70px rgba(0, 0, 0, 0.45)",
    },
    ".cm-mardora-media-lightbox-close": {
      borderColor: "rgba(71, 85, 105, 0.72)",
      backgroundColor: "rgba(15, 23, 42, 0.92)",
      color: "#cbd5e1",
    },
    ".cm-mardora-media-lightbox-close:hover, .cm-mardora-media-lightbox-close:focus-visible": {
      borderColor: "rgba(96, 165, 250, 0.68)",
      color: "#93c5fd",
    },
  },
});
