import { EditorView } from "@codemirror/view";

export const slashMenuTheme = EditorView.baseTheme({
  ".cm-draftly-slash-menu": {
    position: "fixed",
    zIndex: "1000",
    width: "328px",
    maxHeight: "420px",
    overflowY: "auto",
    border: "1px solid rgba(120, 113, 108, 0.22)",
    borderRadius: "12px",
    background: "var(--draftly-slash-bg, #ffffff)",
    boxShadow: "0 18px 48px rgba(15, 23, 42, 0.16)",
    padding: "8px 0 0",
    fontFamily: "var(--font-sans, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif)",
  },
  ".cm-draftly-slash-group": {
    padding: "8px 14px 6px",
    color: "var(--draftly-slash-muted, #a8a29e)",
    fontSize: "12px",
    fontWeight: "700",
  },
  ".cm-draftly-slash-item": {
    display: "grid",
    gridTemplateColumns: "34px 1fr auto",
    alignItems: "center",
    width: "100%",
    minHeight: "34px",
    border: "0",
    padding: "0 14px",
    background: "transparent",
    color: "var(--draftly-slash-fg, #27272a)",
    textAlign: "left",
    cursor: "default",
  },
  ".cm-draftly-slash-item-active": {
    background: "var(--draftly-slash-active, #f4f4f5)",
  },
  ".cm-draftly-slash-icon": {
    color: "var(--draftly-slash-icon, #3f3f46)",
    fontSize: "14px",
    fontWeight: "650",
    textAlign: "center",
  },
  ".cm-draftly-slash-title": {
    overflow: "hidden",
    color: "inherit",
    fontSize: "14px",
    fontWeight: "560",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  ".cm-draftly-slash-hint": {
    marginLeft: "12px",
    color: "var(--draftly-slash-muted, #a8a29e)",
    fontSize: "12px",
    fontWeight: "600",
  },
  ".cm-draftly-slash-footer": {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: "40px",
    marginTop: "6px",
    borderTop: "1px solid rgba(120, 113, 108, 0.18)",
    padding: "0 14px",
    color: "var(--draftly-slash-fg, #27272a)",
    fontSize: "14px",
  },
  ".cm-draftly-slash-footer span:last-child": {
    color: "var(--draftly-slash-muted, #a8a29e)",
    fontSize: "12px",
    fontWeight: "650",
  },
  ".cm-draftly-slash-empty": {
    padding: "14px",
    color: "var(--draftly-slash-muted, #a8a29e)",
    fontSize: "13px",
  },
  "&dark .cm-draftly-slash-menu": {
    "--draftly-slash-bg": "#18181b",
    "--draftly-slash-fg": "#f4f4f5",
    "--draftly-slash-muted": "#a1a1aa",
    "--draftly-slash-active": "#27272a",
    "--draftly-slash-icon": "#e4e4e7",
  },
});
