import { EditorView } from "@codemirror/view";

export const selectionToolbarTheme = EditorView.baseTheme({
  ".cm-markora-selection-toolbar": {
    position: "fixed",
    zIndex: "1001",
    display: "inline-flex",
    alignItems: "center",
    gap: "2px",
    border: "1px solid rgba(24, 24, 27, 0.14)",
    borderRadius: "10px",
    background: "var(--markora-selection-toolbar-bg, #ffffff)",
    boxShadow: "0 14px 38px rgba(15, 23, 42, 0.16)",
    padding: "4px",
    color: "var(--markora-selection-toolbar-fg, #18181b)",
    fontFamily: "var(--font-sans, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif)",
    userSelect: "none",
  },
  ".cm-markora-selection-toolbar-panel": {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    width: "336px",
    gap: "6px",
    padding: "8px",
  },
  ".cm-markora-selection-toolbar-button, .cm-markora-selection-toolbar-link-button": {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "30px",
    height: "30px",
    border: "0",
    borderRadius: "7px",
    background: "transparent",
    color: "inherit",
    cursor: "default",
    padding: "0",
  },
  ".cm-markora-selection-toolbar-button:hover, .cm-markora-selection-toolbar-button-active": {
    background: "var(--markora-selection-toolbar-active, #f4f4f5)",
  },
  ".cm-markora-selection-toolbar-button svg, .cm-markora-selection-toolbar-link-button svg": {
    width: "16px",
    height: "16px",
    strokeWidth: "2",
  },
  ".cm-markora-selection-toolbar-divider": {
    width: "1px",
    height: "22px",
    margin: "0 4px",
    background: "var(--markora-selection-toolbar-border, #e4e4e7)",
  },
  ".cm-markora-selection-toolbar-link-input": {
    boxSizing: "border-box",
    width: "100%",
    border: "0",
    borderRadius: "7px",
    background: "var(--markora-selection-toolbar-input, #f4f4f5)",
    color: "inherit",
    font: "inherit",
    fontSize: "14px",
    outline: "none",
    padding: "8px 10px",
  },
  ".cm-markora-selection-toolbar-link-actions": {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "6px",
  },
  ".cm-markora-selection-toolbar-link-button:hover": {
    background: "var(--markora-selection-toolbar-active, #f4f4f5)",
  },
  ".cm-markora-selection-toolbar-link-button-danger": {
    color: "var(--markora-selection-toolbar-danger, #dc2626)",
  },
  ".cm-markora-selection-toolbar-link-button-danger:hover": {
    background: "var(--markora-selection-toolbar-danger-bg, #fee2e2)",
  },
  ".cm-markora-selection-toolbar-error": {
    color: "var(--markora-selection-toolbar-danger, #dc2626)",
    fontSize: "12px",
    padding: "0 2px",
  },
  ".cm-markora-selection-toolbar-palette-label": {
    color: "var(--markora-selection-toolbar-muted, #71717a)",
    fontSize: "12px",
    padding: "0 2px 4px",
  },
  ".cm-markora-selection-toolbar-swatch-grid": {
    display: "grid",
    gridTemplateColumns: "repeat(8, 24px)",
    gap: "6px",
  },
  ".cm-markora-selection-toolbar-swatch": {
    width: "24px",
    height: "24px",
    border: "1px solid var(--markora-selection-toolbar-border, #e4e4e7)",
    borderRadius: "6px",
    background: "var(--markora-swatch-color, transparent)",
    boxShadow: "inset 0 0 0 1px rgba(255, 255, 255, 0.72)",
    cursor: "default",
    outline: "none",
    padding: "0",
    transition: "border-color 120ms ease, box-shadow 120ms ease, transform 120ms ease",
  },
  ".cm-markora-selection-toolbar-swatch:hover": {
    borderColor: "var(--markora-selection-toolbar-swatch-hover-border, #a1a1aa)",
    boxShadow:
      "0 0 0 3px var(--markora-selection-toolbar-swatch-hover-ring, rgba(24, 24, 27, 0.08)), inset 0 0 0 1px rgba(255, 255, 255, 0.72)",
    transform: "translateY(-1px)",
  },
  ".cm-markora-selection-toolbar-swatch:focus-visible": {
    borderColor: "var(--markora-selection-toolbar-swatch-hover-border, #71717a)",
    boxShadow:
      "0 0 0 3px var(--markora-selection-toolbar-swatch-hover-ring, rgba(24, 24, 27, 0.12)), inset 0 0 0 1px rgba(255, 255, 255, 0.72)",
  },
  "&dark .cm-markora-selection-toolbar": {
    "--markora-selection-toolbar-bg": "#18181b",
    "--markora-selection-toolbar-fg": "#f4f4f5",
    "--markora-selection-toolbar-active": "#27272a",
    "--markora-selection-toolbar-border": "#3f3f46",
    "--markora-selection-toolbar-input": "#27272a",
    "--markora-selection-toolbar-muted": "#a1a1aa",
    "--markora-selection-toolbar-link": "#60a5fa",
    "--markora-selection-toolbar-danger": "#f87171",
    "--markora-selection-toolbar-danger-bg": "rgba(248, 113, 113, 0.18)",
    "--markora-selection-toolbar-swatch-hover-border": "#71717a",
    "--markora-selection-toolbar-swatch-hover-ring": "rgba(244, 244, 245, 0.12)",
  },
});
