import { EditorView } from "@codemirror/view";

export const tocTheme = EditorView.baseTheme({
  ".cm-draftly": {
    position: "relative",
  },
  ".cm-draftly .cm-scroller": {
    boxSizing: "border-box",
    paddingRight:
      "calc(var(--draftly-toc-layout-width, 0px) + var(--draftly-toc-scrollbar-gutter, 0px))",
    scrollbarGutter: "stable",
  },
  ".cm-draftly .cm-scroller::-webkit-scrollbar-track": {
    background: "transparent",
  },
  ".cm-draftly-toc": {
    position: "absolute",
    top: "0",
    right: "var(--draftly-toc-scrollbar-gutter, 0px)",
    bottom: "0",
    zIndex: "8",
    width: "var(--draftly-toc-width, 240px)",
    minWidth: "0",
    borderLeft: "1px solid var(--draftly-toc-border, #ececef)",
    background: "var(--draftly-toc-bg, transparent)",
    color: "var(--draftly-toc-fg, #27272a)",
    userSelect: "none",
  },
  ".cm-draftly-toc[data-draftly-toc-expanded='false']": {
    width: "42px",
  },
  ".cm-draftly-toc-resize": {
    position: "absolute",
    top: "0",
    bottom: "0",
    left: "-4px",
    zIndex: "2",
    width: "8px",
    cursor: "col-resize",
  },
  ".cm-draftly-toc-resize::after": {
    position: "absolute",
    top: "50%",
    left: "3px",
    width: "2px",
    height: "64px",
    borderRadius: "999px",
    background: "var(--draftly-toc-handle, #d4d4d8)",
    opacity: "0",
    transform: "translateY(-50%)",
    transition: "opacity 120ms ease",
    content: "''",
  },
  ".cm-draftly-toc:hover .cm-draftly-toc-resize::after, .cm-draftly-toc-resizing .cm-draftly-toc-resize::after": {
    opacity: "1",
  },
  ".cm-draftly-toc-collapsed svg": {
    width: "16px",
    height: "16px",
  },
  ".cm-draftly-toc-toggle, .cm-draftly-toc-collapsed, .cm-draftly-toc-item": {
    border: "0",
    background: "transparent",
    color: "inherit",
    cursor: "default",
    font: "inherit",
  },
  ".cm-draftly-toc-toggle": {
    position: "absolute",
    top: "8px",
    right: "8px",
    zIndex: "1",
    width: "28px",
    height: "28px",
    borderRadius: "6px",
    color: "var(--draftly-toc-muted, #71717a)",
    opacity: "0.55",
    transition: "background 120ms ease, color 120ms ease, opacity 120ms ease",
  },
  ".cm-draftly-toc-toggle:hover": {
    color: "var(--draftly-toc-active, #18181b)",
    opacity: "1",
  },
  ".cm-draftly-toc-toggle:hover, .cm-draftly-toc-collapsed:hover, .cm-draftly-toc-item:hover": {
    background: "var(--draftly-toc-hover, #f4f4f5)",
  },
  ".cm-draftly-toc-collapsed": {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%",
    color: "var(--draftly-toc-muted, #71717a)",
  },
  ".cm-draftly-toc-list": {
    overflow: "auto",
    height: "100%",
    padding: "12px 10px 16px 18px",
    scrollbarWidth: "thin",
  },
  ".cm-draftly-toc-list::-webkit-scrollbar": {
    width: "8px",
  },
  ".cm-draftly-toc-list::-webkit-scrollbar-track": {
    background: "transparent",
  },
  ".cm-draftly-toc-list::-webkit-scrollbar-thumb": {
    borderRadius: "999px",
    background: "var(--draftly-toc-scrollbar, #c7c7cc)",
  },
  ".cm-draftly-toc-item": {
    display: "block",
    width: "100%",
    overflow: "hidden",
    minHeight: "30px",
    padding: "0 8px",
    borderLeft: "2px solid transparent",
    borderRadius: "6px",
    color: "var(--draftly-toc-muted, #71717a)",
    lineHeight: "30px",
    textAlign: "left",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    transition: "background 120ms ease, color 120ms ease",
  },
  ".cm-draftly-toc-item[data-draftly-toc-level='3']": { paddingLeft: "18px" },
  ".cm-draftly-toc-item[data-draftly-toc-level='4']": { paddingLeft: "28px" },
  ".cm-draftly-toc-item[data-draftly-toc-level='5']": { paddingLeft: "38px" },
  ".cm-draftly-toc-item[data-draftly-toc-level='6']": { paddingLeft: "48px" },
  ".cm-draftly-toc-item-active": {
    borderLeftColor: "var(--draftly-toc-active, #18181b)",
    background: "var(--draftly-toc-hover, #f4f4f5)",
    color: "var(--draftly-toc-active, #18181b)",
    fontWeight: "600",
  },
  ".cm-draftly-toc-empty": {
    padding: "12px 8px",
    color: "var(--draftly-toc-muted, #71717a)",
    fontSize: "13px",
  },
  ".cm-draftly-toc-resizing": {
    userSelect: "none",
  },
  "&dark .cm-draftly-toc": {
    "--draftly-toc-bg": "#18181b",
    "--draftly-toc-fg": "#f4f4f5",
    "--draftly-toc-border": "#3f3f46",
    "--draftly-toc-handle": "#52525b",
    "--draftly-toc-hover": "#27272a",
    "--draftly-toc-muted": "#a1a1aa",
    "--draftly-toc-active": "#f4f4f5",
    "--draftly-toc-scrollbar": "#52525b",
  },
});
