import { EditorView } from "@codemirror/view";

export const tocTheme = EditorView.baseTheme({
  ".cm-draftly": {
    display: "flex",
    alignItems: "stretch",
  },
  ".cm-draftly .cm-scroller": {
    flex: "1 1 auto",
    minWidth: "0",
  },
  ".cm-draftly-toc": {
    position: "relative",
    flex: "0 0 var(--draftly-toc-width, 240px)",
    width: "var(--draftly-toc-width, 240px)",
    minWidth: "0",
    height: "100%",
    borderLeft: "1px solid var(--draftly-toc-border, #e4e4e7)",
    background: "var(--draftly-toc-bg, #ffffff)",
    color: "var(--draftly-toc-fg, #27272a)",
    userSelect: "none",
  },
  ".cm-draftly-toc[data-draftly-toc-expanded='false']": {
    flexBasis: "42px",
    width: "42px",
  },
  ".cm-draftly-toc-resize": {
    position: "absolute",
    top: "0",
    bottom: "0",
    left: "-3px",
    width: "6px",
    cursor: "col-resize",
  },
  ".cm-draftly-toc-resize::after": {
    position: "absolute",
    top: "40%",
    left: "2px",
    width: "2px",
    height: "58px",
    borderRadius: "999px",
    background: "var(--draftly-toc-handle, #d4d4d8)",
    content: "''",
  },
  ".cm-draftly-toc-header": {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: "44px",
    padding: "0 10px 0 14px",
  },
  ".cm-draftly-toc-title": {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "13px",
    fontWeight: "600",
  },
  ".cm-draftly-toc-title svg, .cm-draftly-toc-collapsed svg": {
    width: "16px",
    height: "16px",
  },
  ".cm-draftly-toc-toggle, .cm-draftly-toc-collapsed, .cm-draftly-toc-item": {
    border: "0",
    background: "transparent",
    color: "inherit",
    cursor: "default",
    font: "inherit",
  },
  ".cm-draftly-toc-toggle": {
    width: "28px",
    height: "28px",
    borderRadius: "6px",
  },
  ".cm-draftly-toc-toggle:hover, .cm-draftly-toc-collapsed:hover, .cm-draftly-toc-item:hover": {
    background: "var(--draftly-toc-hover, #f4f4f5)",
  },
  ".cm-draftly-toc-collapsed": {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    gap: "6px",
    width: "100%",
    height: "100%",
    color: "var(--draftly-toc-muted, #71717a)",
    fontSize: "12px",
  },
  ".cm-draftly-toc-list": {
    overflow: "auto",
    height: "calc(100% - 44px)",
    padding: "4px 10px 16px 12px",
  },
  ".cm-draftly-toc-item": {
    display: "block",
    width: "100%",
    overflow: "hidden",
    minHeight: "30px",
    padding: "0 8px",
    borderLeft: "2px solid transparent",
    borderRadius: "6px",
    color: "var(--draftly-toc-muted, #71717a)",
    lineHeight: "30px",
    textAlign: "left",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  ".cm-draftly-toc-item[data-draftly-toc-level='3']": { paddingLeft: "18px" },
  ".cm-draftly-toc-item[data-draftly-toc-level='4']": { paddingLeft: "28px" },
  ".cm-draftly-toc-item[data-draftly-toc-level='5']": { paddingLeft: "38px" },
  ".cm-draftly-toc-item[data-draftly-toc-level='6']": { paddingLeft: "48px" },
  ".cm-draftly-toc-item-active": {
    borderLeftColor: "var(--draftly-toc-active, #18181b)",
    background: "var(--draftly-toc-hover, #f4f4f5)",
    color: "var(--draftly-toc-active, #18181b)",
    fontWeight: "600",
  },
  ".cm-draftly-toc-empty": {
    padding: "12px 8px",
    color: "var(--draftly-toc-muted, #71717a)",
    fontSize: "13px",
  },
  ".cm-draftly-toc-resizing": {
    userSelect: "none",
  },
  "&dark .cm-draftly-toc": {
    "--draftly-toc-bg": "#18181b",
    "--draftly-toc-fg": "#f4f4f5",
    "--draftly-toc-border": "#3f3f46",
    "--draftly-toc-handle": "#52525b",
    "--draftly-toc-hover": "#27272a",
    "--draftly-toc-muted": "#a1a1aa",
    "--draftly-toc-active": "#f4f4f5",
  },
});
